local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", function()
	builtin.find_files({ path_display = { "truncate" } })
end, {})
vim.keymap.set("n", "<leader>fg", function()
	builtin.live_grep({ path_display = { "truncate" } })
end, {})
vim.keymap.set("n", "<leader>fb", builtin.buffers, {})
vim.keymap.set("n", "<leader>fh", builtin.help_tags, {})
