local builtin = require("telescope.builtin")
options = { path_display = { "truncate" } }
vim.keymap.set("n", "<leader>ff", function()
	builtin.find_files(options)
end, {})
vim.keymap.set("n", "<leader>fg", function()
	builtin.live_grep(options)
end, {})
vim.keymap.set("n", "<leader>fs", builtin.grep_string, {})
vim.keymap.set("n", "<leader>fb", builtin.buffers, {})
vim.keymap.set("n", "<leader>fh", builtin.help_tags, {})
