#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".


current_name=$(git config user.name)
current_email=$(git config user.email)
remote=$(git remote -v | grep gitlab.rambler.ru)
target_home_email="grihabor@gmail.com"
target_work_email="grihabor@yandex-team.ru"
target_name="Borodin Gregory"

if [ "$current_name" != "$target_name" ]
then
	echo "$current_name != $target_name"
	exit 1
fi

if [ "$remote" = "" ]
then
	if [ "$current_email" != "$target_home_email" ]
	then
		echo "$current_email != $target_home_email"
		exit 1
	else
		echo OK
	fi
else
	if [ "$current_email" != "$target_work_email" ]
	then
		echo "$current_email != $target_work_email" 
		exit 1
	else 
		echo OK
	fi
fi
