#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".


current_name=$(git config user.name)
current_email=$(git config user.email)
remote=$(git remote -v | grep gitlab.rambler.ru)

if [ "$current_name" != "Borodin Gregory" ]
then
	echo "$current_name != Borodin Gregory"
	exit 1
fi

if [ "$remote" = "" ]
then
	if [ "$current_email" != "grihabor@gmail.com" ]
	then
		echo "$current_email != grihabor@gmail.com"
		exit 1
	else 
		echo OK
	fi
else
	if [ "$current_email" != "g.borodin@rambler-co.ru" ]
	then
		echo "$current_email != g.borodin@rambler-co.ru" 
		exit 1
	else 
		echo OK
	fi
fi
