name: Run linters
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install -y shellcheck=0.10.0
      - run: find bin/ -type f | xargs shellcheck

  shfmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - run: go install mvdan.cc/sh/v3/cmd/shfmt@v3.8.0
      - run: find bin/ -type f | xargs shfmt -d
